name: Node CI
on:
  push:
    branches:
      - '*'
      - '!tmp'
      - '!*.tmp'
      - '!tmp.*'
      - '!temp'
      - '!*.temp'
      - '!temp.*'
      - '!draft'
      - '!*.draft'
      - '!draft.*'
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pnpm:
          - 4.14.0
        vars:
          - id: 0
            node: 12.x
            cmd: pnpm run test:ci
          - id: 1
            node: 14.x
            cmd: pnpm run test:ci
          - id: 2
            node: 14.x
            cmd: pnpx tsc --noEmit
          - id: 3
            node: 14.x
            cmd: pnpm run glob testWithoutCoverage '**/package.json'
          - id: 4
            node: 14.x
            cmd: pnpm run glob testWithoutCoverage '**/*.ts' '**/*.js'
          - id: 5
            node: 14.x
            pnpm: --frozen-lockfile
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.vars.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.vars.node }}
      - name: Cache PNPM store
        uses: actions/cache@v1.1.2
        with:
          path: ~/.pnpm-store
          key: pnpm5-${{ matrix.vars.id }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm5-${{ matrix.vars.id }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            pnpm5-${{ matrix.vars.id }}-
            pnpm5-
      - name: Install pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: ${{ matrix.pnpm }}
          run_install: |
            recursive: true
            args: [ ${{ matrix.vars.pnpm }} ]
      - name: Test
        env:
          SHOW_SPAWN_CMD: 'true'
          CI: 'true'
        run: ${{ matrix.vars.cmd }}
