name: Node CI
on:
  push:
    branches:
      - '*'
      - '!tmp'
      - '!*.tmp'
      - '!tmp.*'
      - '!temp'
      - '!*.temp'
      - '!temp.*'
      - '!draft'
      - '!*.draft'
      - '!draft.*'
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vars:
          - id: 0
            node: 12.x
            cmd: pnpm run test:ci
          - id: 1
            node: 13.x
            cmd: pnpm run test:ci
          - id: 2
            node: 13.x
            cmd: pnpx tsc --noEmit
          - id: 3
            node: 13.x
            cmd: pnpm run glob testWithoutCoverage '**/package.json'
          - id: 4
            node: 13.x
            cmd: pnpm run glob testWithoutCoverage '**/*.ts' '**/*.js'
          - id: 5
            node: 13.x
            pnpm: --frozen-lockfile
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.vars.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.vars.node }}
      - name: Cache PNPM store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ matrix.vars.id }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ matrix.vars.id }}-${{ hashFiles('pnpm-lock.yaml') }}
            pnpm-${{ matrix.vars.id }}-
            pnpm-
      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - name: Install dependencies
        run: pnpm recursive install ${{ matrix.vars.pnpm }}
      - name: Test
        env:
          SHOW_SPAWN_CMD: 'true'
          CI: 'true'
        run: ${{ matrix.vars.cmd }}
